alias yaconf = yay -Pg
alias yaclean = yay -Sc
alias yaclr = yay -Scc
alias yaupg = yay -Syu
alias yasu = yay -Syu --noconfirm
alias yain = yay -S
alias yains = yay -U
alias yare = yay -R
alias yarem = yay -Rns
alias yarep = yay -Si
alias yareps = yay -Ss
alias yaloc = yay -Qi
alias yalocs = yay -Qs
alias yalst = yay -Qe
alias yaorph = yay -Qtd
alias yainsd = yay -S --asdeps
alias yamir = yay -Syy
alias yaupd = yay -Sy
