#!/usr/bin/env bash
#
# sway-wallpaper -- toggle between one fixed wallpaper and a rotation over an
# external directory.
#
#   sway-wallpaper toggle   # what the keybinding does: rotation <-> fixed
#   sway-wallpaper start    # force the rotation on
#   sway-wallpaper stop     # rotation off, back to the fixed wallpaper
#   sway-wallpaper resume   # re-assert the rotation after a sway reload/restart
#   sway-wallpaper status
#
# Settings are read from $XDG_CONFIG_HOME/sway-wallpaper/config, generated by
# modules/gui (WALLPAPER_DIR, WALLPAPER_INTERVAL_SECS, WALLPAPER_DEFAULT).
#
# Runtime state lives in $XDG_RUNTIME_DIR and dies with the login session, so a
# fresh boot always lands on the static `output * background` in sway's config.

set -uo pipefail

config_file="${XDG_CONFIG_HOME:-$HOME/.config}/sway-wallpaper/config"
if [ -r "$config_file" ]; then
  # shellcheck disable=SC1090
  . "$config_file"
fi

wall_dir="${WALLPAPER_DIR:-$HOME/wallpapers}"
interval_secs="${WALLPAPER_INTERVAL_SECS:-900}"
# Empty means: leave whatever sway's own config set up.
default_image="${WALLPAPER_DEFAULT:-}"

if [ -n "${WALLPAPER_EXTRA_PATH:-}" ]; then
  PATH="$WALLPAPER_EXTRA_PATH:$PATH"
fi

# sway exports SWAYSOCK to its children, but a shell spawned by an older sway
# session keeps a dead one (and swaymsg falls back to I3SOCK), so prefer any
# live socket we can find.
find_socket() {
  [ -S "${SWAYSOCK:-}" ] && return 0
  local newest=""
  local candidate
  for candidate in "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"/sway-ipc."$(id -u)".*.sock; do
    [ -S "$candidate" ] || continue
    if [ -z "$newest" ] || [ "$candidate" -nt "$newest" ]; then
      newest="$candidate"
    fi
  done
  if [ -n "$newest" ]; then
    SWAYSOCK="$newest"
    I3SOCK="$newest"
    export SWAYSOCK I3SOCK
  fi
}
find_socket

state_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/sway-wallpaper"
pid_file="$state_dir/rotator.pid"
index_file="$state_dir/index"
current_file="$state_dir/current"

log() { printf 'sway-wallpaper: %s\n' "$*" >&2; }

# sway parses its own command line, so quote the path: names with spaces survive.
# NB: swaybg itself only guarantees PNG and JPEG.
set_background() {
  swaymsg "output * bg \"$1\" fill" >/dev/null 2>&1
}

list_images() {
  find "$wall_dir" -maxdepth 1 -type f -regextype posix-extended \
    -iregex '.*\.(png|jpe?g|webp|bmp|gif)' 2>/dev/null | LC_ALL=C sort
}

read_pid() {
  [ -r "$pid_file" ] || return 1
  local pid
  pid=$(cat "$pid_file" 2>/dev/null) || return 1
  case "$pid" in
    '' | *[!0-9]*) return 1 ;;
  esac
  # PID reuse guard: only our own loop counts as a running rotator.
  [ -r "/proc/$pid/cmdline" ] || return 1
  tr '\0' ' ' <"/proc/$pid/cmdline" | grep -q -- '-loop' || return 1
  printf '%s' "$pid"
}

is_running() {
  local pid
  pid=$(read_pid) || {
    rm -f "$pid_file"
    return 1
  }
  return 0
}

rotate_loop() {
  sleep_pid=""
  on_exit_signal() {
    if [ -n "$sleep_pid" ]; then
      kill "$sleep_pid" 2>/dev/null
    fi
    rm -f "$pid_file"
    exit 0
  }
  trap on_exit_signal TERM INT

  mkdir -p "$state_dir"
  printf '%s' "$$" >"$pid_file"

  while :; do
    if ! swaymsg -t get_version >/dev/null 2>&1; then
      log "no sway compositor reachable, stopping rotation"
      rm -f "$pid_file"
      exit 0
    fi

    images=()
    mapfile -t images < <(list_images)
    count=${#images[@]}

    if [ "$count" -eq 0 ]; then
      log "no images in $wall_dir"
    else
      idx=-1
      if [ -r "$index_file" ]; then
        idx=$(cat "$index_file" 2>/dev/null)
        case "$idx" in
          '' | *[!0-9]*) idx=-1 ;;
        esac
      fi
      idx=$(((idx + 1) % count))
      img="${images[$idx]}"
      printf '%s' "$idx" >"$index_file"
      if set_background "$img"; then
        printf '%s' "$img" >"$current_file"
        log "showing $img"
      else
        log "sway rejected $img"
      fi
    fi

    sleep "$interval_secs" &
    sleep_pid=$!
    wait "$sleep_pid"
  done
}

start() {
  if is_running; then
    log "rotation already running (pid $(read_pid))"
    return 0
  fi
  mkdir -p "$state_dir"
  if command -v setsid >/dev/null 2>&1; then
    setsid nohup "$0" -loop </dev/null >/dev/null 2>&1 &
  else
    nohup "$0" -loop </dev/null >/dev/null 2>&1 &
  fi
  # Let the loop register itself before we return.
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    is_running && return 0
    sleep 0.2
  done
  log "failed to start the rotator"
  return 1
}

stop() {
  local pid
  if pid=$(read_pid); then
    kill "$pid" 2>/dev/null
    for _ in 1 2 3 4 5 6 7 8 9 10; do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.2
    done
    kill -9 "$pid" 2>/dev/null
  fi
  rm -f "$pid_file" "$current_file"
  if [ -n "$default_image" ] && [ -r "$default_image" ]; then
    set_background "$default_image"
  fi
}

resume() {
  is_running || return 0
  local cur=""
  [ -r "$current_file" ] && cur=$(cat "$current_file" 2>/dev/null)
  if [ -n "$cur" ] && [ -r "$cur" ]; then
    set_background "$cur"
  fi
}

status() {
  if is_running; then
    printf 'rotating: every %ss (pid %s)\n' "$interval_secs" "$(read_pid)"
  else
    printf 'static\n'
  fi
  printf 'dir:     %s (%s images)\n' "$wall_dir" "$(list_images | wc -l)"
  if [ -r "$current_file" ]; then
    printf 'current: %s\n' "$(cat "$current_file")"
  else
    printf 'current: (sway default)\n'
  fi
  printf 'default: %s\n' "${default_image:-<sway config>}"
}

case "${1:-toggle}" in
  -loop | loop)
    rotate_loop
    ;;
  start)
    start
    ;;
  stop)
    stop
    ;;
  toggle)
    if is_running; then
      stop
    else
      start
    fi
    ;;
  resume)
    resume
    ;;
  status)
    status
    ;;
  *)
    printf 'usage: sway-wallpaper [toggle|start|stop|resume|status]\n' >&2
    exit 2
    ;;
esac
