format = '''
[╭─ ](surface2)$directory$git_branch$git_status$git_state$package
[╰─ ](surface2)[❯](green) '''

right_format = """$aws$python$cmd_duration$lua"""

palette = "mocha"

[aws]
symbol = " "
force_display = true

[c]
symbol = " "

[directory]
home_symbol = " "
read_only = " 󰌾"
[directory.substitutions]
" /Downloads" = ""
" /Documents" = "󰈙"
" /Music" = ""
" /wallpapers" = ""
" /WORK/" = ": "
" /WORK" = ""

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
behind=" ${behind_count}"
ahead=" ${ahead_count}"
conflicted = "󰞇 ${count}"
untracked = " ${count}"
modified = " ${count}"
staged = " ${count}"
renamed = "󰑕 ${count}"
deleted = "󰚃 ${count}"
stashed = " ${count}"


[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[palettes.mocha]
blue = "#89b4fa"
lavender = "#b4befe"
sapphire = "#74c7ec"
sky = "#89dceb"
teal = "#94e2d5"
green = "#a6e3a1"
yellow = "#f9e2af"
peach = "#fab387"
maroon = "#eba0ac"
red = "#f38ba8"
mauve = "#cba6f7"
pink = "#f5c2e7"
flamingo = "#f2cdcd"
rosewater = "#f5e0dc"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

text = "#cdd6f4"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"

surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"

overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
