#!\bin\bash
# i3 panel config. Powerline style.

font="SauceCodePro Nerd Font:size=12"

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                     # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Icon glyphs from Terminusicons2
icon_clock=""    #"\uf017"                      # Clock icon
icon_calendar="" #"\uf073"
icon_news=""     #"\uf1ea"
icon_cpu=""       #"\u"                 # CPU icon
icon_mem=""      #"\u"                  # MEM icon

icon_charging="󰂄"
icon_battery_5="󰁹" #""  #"\uf240"
icon_battery_4="󰂁" #""  #"\uf241"
icon_battery_3="󰁿" #""  #"\uf242"
icon_battery_2="󰁽"   #""  #"\uf243"
icon_battery_1="󰁻"  #""  #"\uf244"
icon_dl=""         #"\uf0d7"                # Download icon
icon_ul=""         #"\uf0d8"                # Upload icon
icon_vol="󰕾"        #"\uf01a"                # Volume icon
icon_vol_mute="󰝟"
icon_hd=""         #"\uf01c"                # HD / icon
icon_home=""       #"\uf015"                # HD /home icon
icon_wsp=""        #"\uf108"                # Workspace icon
icon_nvd=""

