use-grammars = { except = [ "hare", "wren", "gemini" ] }

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]

# [language.formatter]
# command = "ruff"
# args = [ "format" ]

